### ISSUE TITLE
nfpm_package produces symlinks in the rpm instead of packaging the file.

### ISSUE THREAD

**Issue by leungster** [ericnorris/rules_nfpm#4]
When we specify `contents` using bazel references, the resulting rpm has the symlink instead of the actual file.
```yml
contents:
  - src: "{{ index .Dependencies `@//cmd/rpm:binary}}"
    dst: "/bin/binary"
```

Starting with [nfpm v2.13.0](https://github.com/goreleaser/nfpm/releases/tag/v2.13.0), symlinks are preserved instead of being evaluated. See PR https://github.com/goreleaser/nfpm/pull/453

When `nfpm_package` is used, the bazel-out paths are symlinks back to the execroot. Since those links aren't evaluated, nfpm copies the symlinks as is.

I think the change is to evaluate the symlink [here](https://github.com/ericnorris/rules_nfpm/blob/b4bad369fc2f98b1fef6ab74beb6cf30ede8654b/go/internal/cmd/nfpmwrapper/nfpmwrapper.go#L207) so that the bazel file output is directly referenced by nfpm.
